[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = max_app_8MB.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
    lvgl/lvgl@^8.3.11
    adafruit/Adafruit SHT4x Library@^1.0.4
    https://github.com/strange-v/FT6X36.git
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
